spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://36.41.187.107:3306/dbgirl
    username: root
    password: Ywm@mysql36
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
